

return mimetypes = {
    html   = 'text/html; charset=utf-8',
    xhtml  = 'application/xhtml+xml; charset=utf-8',
    xml    = 'application/xml; charset=utf-8',
    json   = 'application/json; charset=utf-8',
    pdf    = 'application/pdf',
    doc    = 'application/msword',
    xls    = 'application/vnd.ms-excel',
    ppt    = 'application/vnd.ms-powerpoint',
    gif    = 'image/gif',
    jpeg   = 'image/jpeg',
    jpg    = 'image/jpeg',
    png    = 'image/png',
    svg    = 'image/svg+xml; charset=utf-8',
    txt    = 'text/plain; charset=utf-8',
    css    = 'text/css; charset=utf-8',
    js     = 'application/javascript; charset=utf-8',
    zip    = 'application/zip',
    tar    = 'application/x-tar',
    gz     = 'application/gzip',
    mp3    = 'audio/mpeg',
    ogg    = 'audio/ogg',
    wav    = 'audio/wav',
    mp4    = 'video/mp4',
    avi    = 'video/x-msvideo',
    mpg    = 'video/mpeg',
}